# Generated by Django 5.1.3 on 2024-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='return_devolucao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='visualizacao',
        ),
        migrations.AddField(
            model_name='carrinhoproduto',
            name='avaliacao',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
