# Generated by Django 5.1.3 on 2024-11-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_remove_produto_return_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='avaliacao',
        ),
    ]
