# Generated by Django 5.1.3 on 2024-11-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_remove_produto_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordempedido',
            old_name='carro',
            new_name='carrinho',
        ),
    ]
