# Generated by Django 5.1.3 on 2024-11-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_rename_carro_ordempedido_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='user',
        ),
    ]
