# Generated by Django 5.1.3 on 2024-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='ordempedido',
            name='disconto',
        ),
        migrations.RemoveField(
            model_name='ordempedido',
            name='endereco_envio',
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='cep',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='cidade',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='estado',
            field=models.CharField(default=13535135, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='numero',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='rua',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
