# Generated by Django 5.1.3 on 2024-11-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_remove_cliente_bairro_remove_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoproduto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
