# Generated by Django 5.1.3 on 2024-11-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_alter_carrinhoproduto_avaliacao_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordempedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cake.cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cake.ordempedido')),
            ],
        ),
    ]
