# Generated by Django 5.1.3 on 2024-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_ordempedido_cliente_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordempedido',
            name='cvv_cartao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='nome_cartao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='validade_cartao',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
