# Generated by Django 5.1.3 on 2024-11-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0011_ordempedido_cvv_cartao_ordempedido_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordempedido',
            name='cliente',
        ),
    ]
